### ISSUE TITLE
Norton Reservoir

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#980]
Steps:
- [x] create catchment feature at lower dam outlet
- [x] import into vahydro
- [x] add subwatershed model to Norton reservoir catchment feature
- [x] get channel properties 
- [x] set channel properties on model
- [x] connect model to Powell river tributaries folder
- [x] re-segment cbp5 model (see https://github.com/HARPgroup/cbp_wsm/issues/102)

2 reservoirs (in series, upper Lake flows into Lower) total capacity 124 MG (note: total from dam safety docs is 384 acft, ~ 107.5 MG, thus assuming 124 MG is total storage and 16.5 MG unusable). Normal stage set to 67 ft based on volume weighted average between upper and lower ponds.
- Resevoirs (modeled as a single unit)
   - Lower lake: ows-vwuds-intake-info/58783
      - intake `36.916388888900   -82.626666666700`
     - https://apps.dtic.mil/sti/tr/pdf/ADA063516.pdf
     - DA = 0.8 sqmi (according to Natl Dam Safety docs linked above)
   - Upper reservoir
      - https://apps.dtic.mil/sti/tr/pdf/ADA063507.pdf
- Facility: ows-vwuds-intake-info/64932
- #965 

VAHydro
- Facility Feature: ows-vwuds-facility-info/72701
- Facility Model: om-model-info/4826551
- Intake from Lower Lake ows-vwuds-intake-info/64932
- Intake from Robinette Branch ows-vwuds-intake-info/58783
- Reservoir 124 MG (380.54 acft), DA = 0.8 sqmi,
- feature: ows-watershed-dash-info/617491
- Bengees Branch model: om-model-info/7451326/dh_properties
- WSP info: ows-submittal-wsp_plan_system-info/176667?destination=ows-vwuds-facility-info/72701
- River seg: TU3_8883_8880 Powell River above Looney Creek Confluence
- feature: ows-watershed-dash-info/616829/
- model: om-model-info/7426857
- Model for Powell River above Looney Creek: om-model-info/7425758
- HydroID Powell River above Looney Creek = 616829
- Bengees Branch impoundment_fid= 617491,
 
```

```

#### Lower Dam
![image](https://github.com/HARPgroup/vahydro/assets/4571170/c58f9870-c1ae-4238-9065-6e806db9dc9f)

#### Upper Dam
![image](https://github.com/HARPgroup/vahydro/assets/4571170/ed0c1fbe-7bcc-47ff-b166-1695b1c20d83)

**Comment by rburghol** [comment]
Get channel props:
- in Windows: `Rscript.exe /c/usr/local/home/git/vahydro/R/modeling/json/nhd_channel_model_props.R 36.916388888900   -82.626666666700`
- or in linux: `Rscript /opt/model/vahydro/R/modeling/json/nhd_channel_model_props.R 36.916388888900 -82.626666666700`

**Comment by COBrogan** [comment]
We found the NHDPlus catchment using the php script that iterates through segments to create a realistic outlet. We checked the outlet DA with what we might expect from the full NHD segments accessible in NHDPlus tools (~1.12 sq mi)
```
/var/www/html/om$ php get_nhd_basins.php "Benges Branch above Powell River" 36.916388888900 -82.626666666700
	Outlet COMID : 22538984
	Outlet Cumulative Area : 1.1644455013280999
	Outlet Local Area : 3.016
```
Since we found good agreement, we created the corresponding feature to copy over to VAHydro using the same comid and name. We store the results in a temporary file before using the sftp to move it over from the database to VAHydro:
```
psql -h dbase2 va_hydro
  copy (
    select 'Benges Branch above Powell River' as name, comid as hydrocode, 
    st_astext(the_geom) as wkt, 'watershed' as bundle, 'vahydro' as ftype 
    from nhd_fulldrainage 
    where comid = '22538984'
  ) to '/tmp/benges_powell.wkt' WITH HEADER CSV DELIMITER AS E'\t';
  \q
```
Now, add the file onto the database (sftp is the secure file transfer):
```
cd ../files/vahydro/
sftp dbase2
  get /tmp/benges_powell.wkt
  bye
```
Import copied file as a feature. Note the output hydro ID and ftype, which we can query to get the feature ID
```
cd /var/www/html/d.dh
drush scr modules/dh/src/import_features.php /var/www/html/files/vahydro/benges_powell.wkt
	Trying to create feature withArray
	(
		[name] => Benges Branch above Powell River
		[hydrocode] => 22538984
		[bundle] => watershed
		[ftype] => vahydro
	)
	Saving Benges Branch above Powell River 22538984
	Feature ID  617491
```
Create a subwatershed in Local Tribs where 37 is the model interface (will not change for other models), 337676 is the impoundment template, 247403 is the local tributaries template
```
cd ../om
php fn_copy_element.php 37 337676 247403 0
	New object created with elementid 353109
```
So the new Element ID of new model 353109. Now we copy to new VA Hydro database from old model using new model ID and the hydrocode of benges branch catchment
```
cd ../d.dh
drush scr modules/om/src/om.migrate.element.php feature 353109 617491
```
From output, Model PID: 7451326 
Now we can start editing the model. First, set the model to propagate changes back and forth between old model and database. We do this by editing om_element_connection and set to always push changes. Don't forget to update the name of the model and link the new subshed to the parent watershed (which is done from the subshed feature page)

The main properties of the model we will need to edit are the name, description, impoundment stage-storage, the impoundment capcity, and the local channel properties. We can get the local channel properties from nhdplus tools in R
```
Rscript.exe /C:/Users/gcw73279/Desktop/git Backups/OWS/vahydro/R/modeling/json/nhd_channel_model_props.R 36.916388888900 -82.626666666700
```
OR in terminal
```
Rscript /opt/model/vahydro/R/modeling/json/nhd_channel_model_props.R 36.916388888900 -82.626666666700
"length_ft, da_sqmi, cslope 18480.97172 1.12309313935575 0.13106902463383"
```
The results of this script are weighted by area for the NHD segments involved. Note that in this case the script seems to pick up Robinet Branch, which is NOT included in this basin. However, the channel routing is so minor that this will not result in a significant error and is okay to proceed with. The DA may differ slightly from the PHP agglomeration above. Use the values generated by this script, which uses the updated NHDPlus.

We can then set these properties into the local channel object in the model and have it calculate width based on the physiographic province (in this case Appalachian Plateau based on the Staff GIS application). Be sure to update both the total DA (as above from the R script e.g. 1.12) and the local area of the impoundment. This is dependent on the model. In this case, we are going to put the reservoir at the top of the segment and ignore its upstream channel. Instead, the reservoir will feed the second half of Bengees branch. The reservoir has a DA of 0.8 sq mi according to the dam safety fact sheet by the core. So, the local_channel_area is 0.323 (e.g. 1.12 - 0.8 = 0.323). 

For the impoundment, planning data can sometimes provide the storage information. We can get the planning data by looking at the sources tied to our facility page. In addition, we may need to assume an unused capacity, which we usually set at 10% if otherwise unknown (we will use 10% in this model). We can get the SA from the army corps and we'd want the normal pool, so the spillway SA. We set the normal capacity as the model maximum capacity. An storage above this value in the model is automatically routed as flow out from the dam, meaning that we can build the stage-storage of the impoundment out to real-life maximum capacity for reference, but the model will ignore anything above the model input maximum capacity (which again we set as the normal volume of the reservoir). The storage between normal and maximum capacity are likely not consequential in low flow computation.

Now we can transform the Bengees Branch model to set the impoundment at the upstream node. We can also cause the Town of Norton facility model to look at the Bengees Branch impoundment for available withdraw.
```
#Set avail on facility model to look at impoundment storage 
./modules/om/sh/set_reservoir_system_props.sh 4826551
#add new-school discharge calcs to facility model: 
./modules/om/sh/add_discharge_eqs.sh 4826551
#Add imp above channel to Bengees Branch subshed (using pid): 
./modules/om/sh/add_impoundment_above_channel.sh 7451326
```
The Town of Norton discharges to a different watershed/river (see the regional treatment plant Coeburn Norton Wise Regional WWTP VA0077828). So, we will send the discharge out of the model using PS other such that it is not returned to the Powell. 
To do this, we edit ps_enabled and set it to the ps_other value for all run modes.

Under model element and run summary info we put comments about where we got the model inputs, any changes we made compared to a "standard" run. In this case, this will included how we made a combined reservoir from the two, how the PS goes elsewhere and why, and how we set up the trib to have the impoundment at the top of the catchment

We also need to resegment the Bay model. This doesn't affect the OM model, but will impact future runs via the meta model, making it easier and more accurate for our purposes when we run future simulations using the HSP scenario subsheds.
Powell River above Looney Creek = TU3_8883_8880
Bengees Branch HydroID in form of: vahydrosw_wshed_TU3_8884_8880 (note that this usually begins as a hydrocode, but is here a rseg ID since I added this segment incorrectly to the Powell not the Powell above Looney. We update these manually later on. See below)
```
./run/resegment/add_sub_watershed.bat TU3_8884_8880 TU3_8883_8880 cbp-6.1 subsheds 1.12309313935575
```
Following this, you change the hydrocode of bengees branch to that output by the model as: vahydrosw_wshed_RIVSEGIDHERE. Run the following to generate the basin list/file for the Bay Model to create the segment list:
```
cbp basingen.csh subsheds 8880
#Check to ensure new basin is in the list:
cbp get_riversegs TU3_8880_9230
```
#For mistakes, we can remove resegmentation with first input is that to be removed, second is that to remove it from
./run/resegment/remove_sub_watershed.bat TU3_8884_8880 TU3_8880_9230 cbp-6.1 subsheds 1.12309313935575
